### ISSUE TITLE
Tournament Checklist Jun/22

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#1]
- [x] NRG 10k Trial Lansing (Modern): https://mtgmelee.com/Tournament/View/9604
- [x] NRG 5k Trial Lansing (Pioneer): https://mtgmelee.com/Tournament/View/9605
- [x] Manatraders July/22 (Modern): https://www.manatraders.com/tournaments/28
- [x] MOCS Season 1: https://magic.gg/decklists/2022-magic-online-champions-showcase-season-1-modern-decklists

**Comment by Badaro** [comment]
Leave a comment below if you have any tournament you want added to the dataset.
