### ISSUE TITLE
Reingest MtgMelee site data after improvements

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#17]
There's two pending improvements for the mtgmelee scraper, documented in #12 and #13. Once those are implemened we should reingest all data.

- [x] Implement improvement documented in #12 
- [x] Implement improvement documented in #13
- [x] Review normalization as described in #18
- [ ] Perform a full reingest of data
