### ISSUE TITLE
Tournament Checklist Jul/22

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#2]
- [x] Manatraders July/22 (Vintage): https://www.manatraders.com/tournaments/29
- [x] SCG Syracuse Trial Friday 1PM: https://mtgmelee.com/Tournament/View/10152
- [x] SCG Syracuse Trial Friday 4PM: https://mtgmelee.com/Tournament/View/10153
- [x] SCG Syracuse Modern Challenge 30k: https://mtgmelee.com/Tournament/View/10155
- [x] SCG Syracuse Modern 5K Sunday 9AM: https://mtgmelee.com/Tournament/View/10156
- [x] SCG Syracuse Legacy 5K Sunday 10AM: https://mtgmelee.com/Tournament/View/10157
- [x] NRG Series $10,000 Trial - Chicagoland (Modern): https://mtgmelee.com/Tournament/View/9606
- [x] NRG Series $5,000 Trial - Chicagoland (Legacy): https://mtgmelee.com/Tournament/View/9607
