### ISSUE TITLE
Tournament Checklist Dec/22

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#22]
- [x] South America Magic Series - Regional Championship (Final Regional Dec 2022) (Pioneer): https://mtgmelee.com/Tournament/View/13040
- [x] F2F Tour Championship -Calgary Cycle 1 (Regional Championship) (Pioneer): https://mtgmelee.com/Tournament/View/11822
- [x] NRG Series $15,000 Showdown - Louisville (Modern): https://mtgmelee.com/Tournament/View/11722
- [x] NRG Series $5,000 Trial - Louisville (Pioneer): https://mtgmelee.com/Tournament/View/11723
- [x] 2022 NA Vintage Championship: https://mtgmelee.com/Tournament/View/12792
- [x] 2022 NA Legacy Championship: https://mtgmelee.com/Tournament/View/12793
- [x] Grand Open Qualifier Barcelona (Modern): https://mtgmelee.com/Tournament/View/12522
- [x] The Gathering: Showdown Series (Pioneer): https://mtgmelee.com/Tournament/View/12862
