### ISSUE TITLE
Tournament Checklist Jan/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#23]
- [x] Modern $20K Trial - SCG CON New Jersey - Friday - 4:00 pm (Silver): https://mtgmelee.com/Tournament/View/13191
- [x] Legacy $10K Trial - SCG CON New Jersey - Friday - 4:00 pm (Silver): https://mtgmelee.com/Tournament/View/13193
- [x] Modern $20K Trial - SCG CON New Jersey - Friday - 1:00 pm (Silver): https://mtgmelee.com/Tournament/View/13190
- [x] Legacy $10K Trial - SCG CON New Jersey - Friday - 1:00 pm (Silver): https://mtgmelee.com/Tournament/View/13192
- [x] Legacy $10K - SCG CON New Jersey - Saturday - 9:00 am (Gold): https://mtgmelee.com/Tournament/View/13195
- [x] $20K RCQ (Top 4) - Modern - SCG CON New Jersey - Saturday - 10:00 am: https://mtgmelee.com/Tournament/View/13194
- [x] Legacy $5K - SCG CON New Jersey - Sunday - 9:30 am: https://mtgmelee.com/Tournament/View/13197
- [x] $5K RCQ - Modern - SCG CON New Jersey - Sunday - 9:00 am: https://mtgmelee.com/Tournament/View/13196
- [x] Grand Open Qualifier Trieste (Modern): https://mtgmelee.com/Tournament/View/13431
- [x] Classic Qualifier Trieste (Modern): https://mtgmelee.com/Tournament/View/13432
