### ISSUE TITLE
Tournament Checklist Mar/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#28]
- [x] [Modern $20K Trial - SCG CON Charlotte - Friday - 1:00 pm (Silver)](https://mtgmelee.com/Tournament/View/14033)
- [x] [Modern $20K Trial - SCG CON Charlotte - Friday - 4:00 pm (Silver)](https://mtgmelee.com/Tournament/View/14034)
- [x] [*Special $20 Entry!* - $20K RCQ (Top 4) - Modern - SCG CON Charlotte - Saturday - 10:00 am](https://mtgmelee.com/Tournament/View/14035)
- [x] [*Special $10 Entry!* - $10K RCQ (Top 2) - Modern - SCG CON Charlotte - Sunday - 9:00 am](https://mtgmelee.com/Tournament/View/14036)
- [x] [プレイヤーズコンベンションオープン横浜 2023　モダンオープン](https://mtgmelee.com/Tournament/View/13617)
- [x] [ANZ Super Series Sunday 5K - Cycle 2](https://mtgmelee.com/Tournament/View/14651)
- [x] [CCG Super Qualifier - Ciclo 3](https://mtgmelee.com/Tournament/View/14603)
- [x] [2023 Hunter Burton Memorial Open](https://mtgmelee.com/Tournament/View/13072)
- [x] [HBMO23 - Dave & Adams Legacy 2k](https://mtgmelee.com/Tournament/View/13878)
- [x] [HBMO23 - Common Ground Sunday Pioneer 5k](https://mtgmelee.com/Tournament/View/13078)
- [x] [NRG Series $10,000 Trial - Chicagoland (Modern)](https://mtgmelee.com/Tournament/View/14056)
- [x] [NRG Series $5,000 Trial - Chicagoland (Pioneer)](https://mtgmelee.com/Tournament/View/14058)
- [x] [MXP Oakland Mar 31 Modern 20k 1pm Trials](https://mtgmelee.com/Tournament/View/12803)
- [x] [MXP Oakland Mar 31 Modern 20k 3pm Trials](https://mtgmelee.com/Tournament/View/12804)
- [x] [MXP Oakland Mar 31 Modern 20k 5pm Trials](https://mtgmelee.com/Tournament/View/12805)

**Comment by uberidiot** [comment]
Hello!

More suggested tournaments from MtgMelee and March 2023.

I retrieved all of them and removed the ones with URI already here. I didn't know your threshold, so I removed all tournaments with less than 10 decks and sorted by number of decks.

Attached as tab-separated plain text for easy automatization.

[mtgmelee_march_23.txt](https://github.com/Badaro/MTGODecklistCache/files/11105681/mtgmelee_march_23.txt)

EDIT: Forgot to say I only did Modern, Pioneer, Legacy and Pauper.

**Comment by uberidiot** [comment]
After the filtering discussed in Issue #31 , only one tournament from March 2023 survived.

[mtgmelee_2023-03_only.txt](https://github.com/Badaro/MTGODecklistCache/files/11115716/mtgmelee_2023-03_only.txt)

**Comment by Badaro** [comment]
Added to the checklist. I'm going to take a coffee break now and will also add this tournament.

**Comment by Badaro** [comment]
Just noticed it's a february tournament. Some filtering error? :D

```Modern	81	96	2023-02-11	YungDingo	Doghouse V: Cupid Shuffle	https://mtgmelee.com/Tournament/View/14115```

Looking at the other file you probably wanted to post this one, right?

```Legacy	61	2023-03-04	Buffalo Chicken Dip Legacy 11	https://mtgmelee.com/Tournament/View/13647```

We'll handle the other one on #31.

**Comment by uberidiot** [comment]
In the immortal words of Bubbles... something's fucky.

Nah, I just was tripped by the lonely 2023 in the big list. No tournament from March survived the filter. That Buffalo Chicken Dip one had 64 players, in the limit to not pass.

Just for posterity, I'll attach a text file with that tournament, like it would have been.

[mtgmelee_2023-03_only.txt](https://github.com/Badaro/MTGODecklistCache/files/11116385/mtgmelee_2023-03_only.txt)
