### ISSUE TITLE
Tournament Checklist Aug/22

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#3]
- [x] Manatraders August/22 (Pioneer): https://www.manatraders.com/tournaments/30
- [x] Grand Open Qualifier Copenhagen: https://mtgmelee.com/Tournament/View/11417
- [x] SCG CON Baltimore - Team Constructed $25K: https://mtgmelee.com/Tournament/View/10843
- [x] SCG CON Baltimore - Modern $5K: https://mtgmelee.com/Tournament/View/10847
- [x] SCG CON Baltimore - Pioneer $5K: https://mtgmelee.com/Tournament/View/10848
- [x] SCG CON Baltimore - Legacy $5K: https://mtgmelee.com/Tournament/View/10846
- [x] NRG Series $20,000 Showdown - St. Louis (Team): https://mtgmelee.com/Tournament/View/9609
- [x] NRG Series $5,000 Trial - St. Louis (Modern): https://mtgmelee.com/Tournament/View/9610
- [x] MTG SEA Championships Philippine Open: https://mtgmelee.com/Tournament/View/11411
