### ISSUE TITLE
Tournament Checklist Apr/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#32]
- [x] [Grand Open Qualifier Prague](https://mtgmelee.com/Tournament/View/14914)
- [x] [Bazaar of Boxes Series 7](https://mtgmelee.com/Tournament/View/14169)
- [x] [MXP Oakland Apr 1 Modern 20k RCQ - 4 Slots](https://mtgmelee.com/Tournament/View/12794)
- [x] [MXP Oakland Apr 1 Legacy 5k](https://mtgmelee.com/Tournament/View/12828)
- [x] [MXP Oakland Apr 2 Pioneer 5k RCQ - 1 Slot](https://mtgmelee.com/Tournament/View/12802)
- [x] [Modern $20K Trial - SCG CON Richmond - Friday - 11:00 am (Silver)](https://mtgmelee.com/Tournament/View/14565)
- [x] [Modern $20K Trial - SCG CON Richmond - Friday - 1:30 pm (Silver)](https://mtgmelee.com/Tournament/View/14566)
- [x] [ReCQ - Pioneer - SCG CON Richmond - Friday - 2:00 pm (Bronze)](https://mtgmelee.com/Tournament/View/14570)
- [x] [Modern $20K Trial - SCG CON Richmond - Friday - 4:00 pm (Silver)](https://mtgmelee.com/Tournament/View/14567)
- [x] [$20K RCQ (Top 4) - Modern - SCG CON Richmond - Saturday - 10:00 am](https://mtgmelee.com/Tournament/View/14572)
- [x] [ReCQ - Modern - SCG CON Richmond - Saturday - 2:00 pm (Bronze)](https://mtgmelee.com/Tournament/View/14604)
- [x] [$5K RCQ - Modern - SCG CON Richmond - Sunday - 9:00 am](https://mtgmelee.com/Tournament/View/14573)
- [x] [ReCQ - Pioneer - SCG CON Richmond - Sunday - 12:00 pm (Bronze)](https://mtgmelee.com/Tournament/View/14605)
