### ISSUE TITLE
Tournament Checklist May/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#35]
- [x] [NRG Series $10,000 Showdown - Minneapolis (Pioneer)](https://melee.gg/Tournament/View/14059)
- [x] [NRG Series $5,000 Trial - Minneapolis (Modern)](https://melee.gg/Tournament/View/14060)
- [x] [Grand Open Qualifier Valencia (Pioneer)](https://melee.gg/Tournament/View/15192)
- [x] [Classic Qualifier Valencia (Modern)](https://melee.gg/Tournament/View/15193)
