### ISSUE TITLE
Tournament Checklist Jun/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#36]
- [x] [Dreamhack Dallas 2023 - Sat. 9:30 AM U.S. Regional Championship (Pioneer)](https://melee.gg/Tournament/View/15367)
- [x] [DreamHack Dallas 2023 - Sun. 10AM Pioneer 10k Open 8-Slot RCQ](https://melee.gg/Tournament/View/15942)
- [x] [DreamHack Dallas 2023 - Sun. 11AM Pioneer 5k Open 8-Slot RCQ](https://melee.gg/Tournament/View/16271)
- [x] [F2F Tour Championship - Toronto Round 3 (Regional Championship) (Pioneer)](https://melee.gg/Tournament/View/15170)
- [x] [MTG SEA Championship Final Cycle 3 (Pioneer)](https://melee.gg/Tournament/View/15656)
- [x] [龙盾杯 MTC China Open S3 Regional Championship (Pioneer)](https://melee.gg/Tournament/View/15616)
- [x] [The Gathering Showdown Series (Pioneer)](https://melee.gg/Tournament/View/15498)
- [x] [Legacy European Championship Athens (Pioneer)](https://melee.gg/Tournament/View/15288)
- [x] [Classic Qualifier Athens (Pioneer)](https://melee.gg/Tournament/View/15290)
- [x] [Charlie's Collectible Show Presents 5k Modern Magic Tournament](https://melee.gg/Tournament/View/15992)
- [x] [MIT Championship 台灣冠軍賽-第三循環 (Pioneer)](https://melee.gg/Tournament/View/15416)
- [x] [ReCQ - Modern - SCG CON Baltimore - Friday - 2:00 pm (Bronze)](https://melee.gg/Tournament/View/15701)
- [x] [ReCQ - Modern - SCG CON Baltimore - Saturday - 1:00 pm (Bronze)](https://melee.gg/Tournament/View/15702)
- [x] [ReCQ - Modern - SCG CON Baltimore - Sunday - 12:00 pm (Bronze)](https://melee.gg/Tournament/View/15703)
- [x] [$5K Legacy - SCG CON Baltimore - Sunday - 9:00 am](https://melee.gg/Tournament/View/15708)
- [x] [$10K Legacy - SCG CON Baltimore - Saturday - 9:00 am](https://melee.gg/Tournament/View/15707)
- [x] [F2F Tour Championship -Edmonton Round 3 (Regional Championship) (Pioneer)](https://melee.gg/Tournament/View/15169)
- [x] [Oklahoma Land Run '23 Legacy Open](https://melee.gg/Tournament/View/14630)
- [x] [プレイヤーズコンベンション千葉 2023　モダンオープン　Players Convention '23 Modern Open](https://melee.gg/Tournament/View/15431)
- [x] [プレイヤーズコンベンション千葉 2023　パイオニアオープン　Players Convention '23 Pioneer Open](https://melee.gg/Tournament/View/15432)
- [x] [チャンピオンズカップファイナル　サイクル3　Champions Cup Final Cycle 3 (Pioneer)](https://melee.gg/Tournament/View/15397)
- [x] [ANZ Super Series Final Cycle Three- Sydney (Pioneer)](https://melee.gg/Tournament/View/13419)
- [x] [NRG Series $10,000 Showdown - Chicagoland (Modern)](https://melee.gg/Tournament/View/14061)
- [x] [NRG Series $5,000 Trial - Chicagoland (Legacy)](https://melee.gg/Tournament/View/14062)
