### ISSUE TITLE
Tournament Checklist Jul/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#37]
- [x] [South America Magic Series - Regional Championship (Final Regional Jun 2023) (Pioneer)](https://melee.gg/Tournament/View/15828)
- [x] [City Class Games Showdown IlI (Pioneer)](https://melee.gg/Tournament/View/15524)
- [x] [CCG SUPERQUALIFIER 5K OPEN (Pioneer)](https://melee.gg/Tournament/View/16740)
- [x] [Bazaar of Boxes Series 8 (Legacy)](https://melee.gg/Tournament/View/15684)
- [x] [Grand Open Qualifier Bologna (Modern)](https://melee.gg/Tournament/View/16657)
- [x] [Classic Qualifier Bologna (Pioneer)](https://melee.gg/Tournament/View/16658)
- [x] [NRG Series $10,000 Showdown - St. Louis, Missouri (Team Trios Constructed)](https://melee.gg/Tournament/View/15645)
- [x] [NRG Series $5,000 Trial - St. Louis, Missouri (Legacy)](https://melee.gg/Tournament/View/15649)
- [x] [$25K RCQ (Winning Team) - Team Constructed - SCG CON Cincinnati - Saturday - 10:00 am](https://melee.gg/Tournament/View/16136)
- [x] [ReCQ - Modern - SCG CON Cincinnati - Friday - 2:00 pm (Bronze)](https://melee.gg/Tournament/View/16129)
- [x] [ReCQ - Pioneer - SCG CON Cincinnati - Saturday - 2:00 pm (Bronze)](https://melee.gg/Tournament/View/16130)
- [x] [ReCQ - Modern - SCG CON Cincinnati - Sunday - 12:00 pm (Bronze)](https://melee.gg/Tournament/View/16134)
- [x] [$5K RCQ - Modern - SCG CON Cincinnati - Sunday - 9:00 am](https://melee.gg/Tournament/View/16137)
- [x] [$5K RCQ - Pioneer - SCG CON Cincinnati - Sunday - 9:30 am](https://melee.gg/Tournament/View/16138)
- [x] [$5K Legacy - SCG CON Cincinnati - Sunday - 10:00 am](https://melee.gg/Tournament/View/16139)
- [x] [Pro Tour The Lord of the Rings](https://melee.gg/Tournament/View/16429)
- [x] [Buffalo Chicken Dip Legacy Open 2](https://melee.gg/Tournament/View/15010)
- [x] [Mont - Pauper 2K](https://melee.gg/Tournament/View/17267)
- [x] [SUN 9AM - Pro Tour Competitor Second Chance PTQ](https://melee.gg/Tournament/View/16772)
