### ISSUE TITLE
Tournament Checklist Aug/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#38]
- [x] MXP Tacoma Aug 11 Re-CQ (Modern) (https://melee.gg/Tournament/View/16076)
- [x] MXP Tacoma Aug 12 Re-CQ (Modern) (https://melee.gg/Tournament/View/16077)
- [x] MXP Tacoma Aug 13 Re-CQ (Modern) (https://melee.gg/Tournament/View/16078)
- [x] MXP Tacoma Aug 12 Modern 20k RCQ - 4 Slots (https://melee.gg/Tournament/View/16075)
- [x] MXP Tacoma Aug 12 Legacy 5k (https://melee.gg/Tournament/View/16079)
- [x] NRG Series $10,000 Showdown - Detroit, Michigan (Modern) (https://melee.gg/Tournament/View/15650)
- [x] NRG Series $5,000 Trial - Detroit, Michigan (Pioneer) (https://melee.gg/Tournament/View/15651)
- [x] Kadou Series Modern (https://melee.gg/Tournament/View/19222
- [x] 1K Pioneer (https://melee.gg/Tournament/View/15489)
- [x] 5K Legacy (https://melee.gg/Tournament/View/15490)
- [x] Doghouse VI: Lord of the Bings (Modern) (https://melee.gg/Tournament/View/17364)
- [x] Modern 10K (2-Slot RCQ Destination) (https://melee.gg/Tournament/View/15485)
- [x] CCG Super Qualifier Pioneer 5K - Kino Weekend (https://melee.gg/Tournament/View/18446)
- [x] 5K Pioneer RCQ (Destination) (https://melee.gg/Tournament/View/15491)
