### ISSUE TITLE
Tournament Checklist Sep/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#39]
- [x] Nordic Masters - Legacy (https://melee.gg/Tournament/View/17763)
- [x] Nordic Masters - Modern (https://melee.gg/Tournament/View/17761)
- [x] Modern $20K Trial - SCG CON Columbus - Friday - 1:00 pm (Silver) (https://melee.gg/Tournament/View/16955)
- [x] Modern $20K Trial - SCG CON Columbus - Friday - 4:00 pm (Silver) (https://melee.gg/Tournament/View/16956) 
- [x] ReCQ - Pioneer - SCG CON Columbus - Friday - 2:00 pm (Bronze) (https://melee.gg/Tournament/View/16958)
- [x] ReCQ - Pioneer - SCG CON Columbus - Saturday - 1:00 pm (Bronze) (https://melee.gg/Tournament/View/16959)
- [x] ReCQ - Pioneer - SCG CON Columbus - Sunday - 12:00 pm (Bronze) (https://melee.gg/Tournament/View/16960)
- [x] $5K RCQ - Modern - SCG CON Columbus - Sunday - 9:00 am (https://melee.gg/Tournament/View/16957)
- [x] $20K RCQ (Top 4) - Modern - SCG CON Columbus - Saturday - 10:00 am (https://melee.gg/Tournament/View/16954)
- [x] C'mon! Katowice (Pauper) (https://melee.gg/Tournament/View/17122)
- [x] Modern 5K Apex Invitational Qualifier (https://melee.gg/Tournament/View/23251)
- [x] Pioneeer 2K Apex Invitational Qualifier (https://melee.gg/Tournament/View/23253)
- [x] 7º LPL OPEN - SEASON IV - Liga Paulista Legacy (https://melee.gg/Tournament/View/21353)
- [x] RED- FRI- 3PM - Secret Lair Showdown Qualifier - Modern - Single Elimination (https://melee.gg/Tournament/View/24570)
- [x] BLACK - SAT - 11AM - Secret Lair Showdown Qualifier - Modern - Single Elimination (https://melee.gg/Tournament/View/24572)
- [x] BLACK - SAT - 1PM - Secret Lair Showdown Qualifier - Modern - Single Elimination (https://melee.gg/Tournament/View/24573)
- [x] BLACK - SAT - 3PM - Secret Lair Showdown Qualifier - Modern - Single Elimination (https://melee.gg/Tournament/View/24574)
- [x] Secret Lair Showdown Championship (Modern) (https://melee.gg/Tournament/View/24589)
- [x] Last Chance Qualifier Lille (Pioneer) (https://melee.gg/Tournament/View/16659)
- [x] Legacy European Championship Lille (Pioneer) (https://melee.gg/Tournament/View/16639)
- [x] RADIOATOG VOL.3 - TEAM TRIO PAUPER (https://melee.gg/Tournament/View/17900)
- [x] F2F Tour Championship - Calgary Round 4 (Regional Championship)(Pioneer) (https://melee.gg/Tournament/View/17095)
