### ISSUE TITLE
Tournament Checklist Sep/22

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#4]
- [x] Manatraders September/22 (Standard): https://www.manatraders.com/tournaments/31
- [x] SCG Columbus Modern $10k: https://mtgmelee.com/Tournament/View/11112
- [x] SCG Columbus Modern $20k (Fri-Sat): https://mtgmelee.com/Tournament/View/11110
- [x] SCG Columbus Modern $20k (Sat-Sun): https://mtgmelee.com/Tournament/View/11111
- [x] Grand Open Qualifier Paris: https://mtgmelee.com/Tournament/View/11813
- [x] MTG SEA Championships Singapore Open: https://mtgmelee.com/Tournament/View/11923
- [x] NRG Series $10,000 Trial - Minneapolis (Modern): https://mtgmelee.com/Tournament/View/10501
- [x] NRG Series $5,000 Trial - Minneapolis (Pioneer): https://mtgmelee.com/Tournament/View/10502
