### ISSUE TITLE
Tournament Checklist Oct/23

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#42]
- [x] [Classic Qualifier Lille (Pioneer)](https://melee.gg/Tournament/View/16660)
- [x] [MXP Portland Oct 13 ReCQ (Modern)](https://melee.gg/Tournament/View/17463)
- [x] [MXP Portland Oct 14 Legacy 5k](https://melee.gg/Tournament/View/17461)
- [x] [MXP Portland Oct 14 ReCQ (Modern)](https://melee.gg/Tournament/View/17468)
- [x] [MXP Portland Oct 14 Modern 20k RCQ - 4 Slots](https://melee.gg/Tournament/View/17459)
- [x] [MXP Portland Oct 15 Pioneer 5k RCQ](https://melee.gg/Tournament/View/17462)
- [x] [MXP Portland Oct 15 ReCQ (Modern)](https://melee.gg/Tournament/View/17469)
- [x] [NRG Series $10,000 Showdown - Indianapolis, Indiana (Pioneer)](https://melee.gg/Tournament/View/15652)
