### ISSUE TITLE
Tournament Checklist Oct/22

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#5]
- [x] Manatraders October/22 (Pioneer): https://www.manatraders.com/tournaments/32
- [x] Grand Open Qualifier Amsterdam: https://mtgmelee.com/Tournament/View/12103
- [x] Abra Roberts Modern Memorial: https://mtgmelee.com/Tournament/View/11996
- [x] The Legacy Pit Open II: https://mtgmelee.com/Tournament/View/11997
- [x] MOCS Season 2 (Pioneer): https://magic.gg/decklists/2022-magic-online-champions-showcase-season-2-pioneer-decklists
- [x] Modern $30K - SCG CON Dallas - Saturday - 10:00 am: https://mtgmelee.com/Tournament/View/11807
- [x] Modern $5K - SCG CON Dallas - Sunday - 9:00 am: https://mtgmelee.com/Tournament/View/11808
- [x] Modern Trial - SCG CON Dallas - Friday - 4:00 pm: https://mtgmelee.com/Tournament/View/11811
- [x] Modern Trial - SCG CON Dallas - Friday - 1:00 pm: https://mtgmelee.com/Tournament/View/11810
- [x] Pioneer $5K - SCG CON Dallas - Sunday - 9:30 am: https://mtgmelee.com/Tournament/View/11809
- [x] Grand Open Qualifier Warsaw: https://mtgmelee.com/Tournament/View/12280
- [x] NRG Series $10,000 Trial - Newark, Ohio (Team Constructed): https://mtgmelee.com/Tournament/View/11715
- [x] NRG Series $5,000 Trial - Newark, Ohio (Modern): https://mtgmelee.com/Tournament/View/11716

Old Tournaments:
- [x] The Legacy Pit Open: https://mtgmelee.com/Tournament/View/7720
