### ISSUE TITLE
Tournament Checklist Nov/22

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGODecklistCache#6]
- [x] Manatraders November/22 (Modern): https://www.manatraders.com/tournaments/33
- [x] NRG Series $5,000 Trial - Fort Wayne (Pioneer): https://mtgmelee.com/Tournament/View/11718
- [x] NRG Series $10,000 Trial - Fort Wayne (Team Constructed): https://mtgmelee.com/Tournament/View/11717
- [x] Pioneer Trial - SCG CON Philadelphia - Friday - 1:00 pm: https://mtgmelee.com/Tournament/View/11888
- [x] Pioneer Trial - SCG CON Philadelphia - Friday - 4:00 pm: https://mtgmelee.com/Tournament/View/11889
- [x] Pioneer $30K RCQ (Top 4) - SCG CON Philadelphia - Saturday - 10:00 am: https://mtgmelee.com/Tournament/View/11890
- [x] Pioneer $5K RCQ - SCG CON Philadelphia - Sunday - 9:30 am: https://mtgmelee.com/Tournament/View/11892
- [x] Modern $5K RCQ - SCG CON Philadelphia - Sunday - 9:00 am: https://mtgmelee.com/Tournament/View/11891
- [x] City Class Games Showdown I (Pioneer): https://mtgmelee.com/Tournament/View/12349
- [x] Last Chance Qualifier Sofia (Pioneer): https://mtgmelee.com/Tournament/View/12519
- [x] Legacy European Championship Sofia (Pioneer): https://mtgmelee.com/Tournament/View/12521
- [x] Dreamhack Atlanta 2022 - Sat. 10AM U.S. Regional Championship (Pioneer): https://mtgmelee.com/Tournament/View/12649
- [x] Dreamhack Atlanta 2022 - Sun. 10AM Pioneer $10k Open 8-slot RCQ: https://mtgmelee.com/Tournament/View/12670
- [x] ANZ Super Series Final - Sydney (Pioneer): https://mtgmelee.com/Tournament/View/12737
- [x] Player's Convention Open 2022 (Pioneer) https://mtgmelee.com/Tournament/View/12380
- [x] Champions Cup Final Cycle1 (Pioneer): https://mtgmelee.com/Tournament/View/12374
- [x] 2022 Asia Vintage Championship: https://mtgmelee.com/Tournament/View/12410
- [x] 2022 Asia Legacy Championship: https://mtgmelee.com/Tournament/View/12412
- [x] MTG SEA Championship Final Cycle 1 (Pioneer): https://mtgmelee.com/Tournament/View/12857
- [x] NRG Series $10,000 Trial - Chicagoland (Pioneer): https://mtgmelee.com/Tournament/View/11719
- [x] F2F Tour Championship - Toronto Cycle 1 (Regional Championship) (Pioneer): https://mtgmelee.com/Tournament/View/11821
- [x] NRG Series $5,000 Trial - Chicagoland (Modern)]: https://mtgmelee.com/Tournament/View/11721
